[package]
name = "poly-fit"
version = "0.1.0"
authors = ["CarlyRaeJepsenStan <711flametrooper@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.29.0"
